version: '3.8'
services:
  dev-db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: market
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 1234qwer!
    restart: always
    networks:
      - market
networks:
  market: